# Generated by Django 2.1.15 on 2020-06-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teste',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
