# Generated by Django 2.1.15 on 2020-06-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teste',
        ),
    ]
